"""GitHub integration — push workspace files and open a PR."""

import logging
import re
from pathlib import Path

from github import Auth, Github

from config import Settings
from schemas import CodeOutput, ReviewOutput, SpecOutput

logger = logging.getLogger("github")
settings = Settings()


def _slugify(text: str, max_len: int = 50) -> str:
    """Convert text to a branch-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_len]


def create_pr(
    spec: SpecOutput,
    code: CodeOutput,
    review: ReviewOutput | None,
    iteration: int = 0,
) -> str | None:
    """Push workspace files to a new branch and open a PR.

    Returns the PR URL, or None if GitHub is not configured.
    """
    if not settings.github_token or not settings.github_repo:
        logger.info("GitHub not configured — skipping PR creation")
        return None

    token = settings.github_token.get_secret_value()
    g = Github(auth=Auth.Token(token))
    repo = g.get_repo(settings.github_repo)

    # Create branch from base
    base_branch = repo.get_branch(settings.github_base_branch)
    branch_name = f"dev-team/{_slugify(spec.title)}"

    try:
        repo.get_git_ref(f"heads/{branch_name}")
        logger.warning("Branch %s already exists — appending suffix", branch_name)
        import uuid
        branch_name += f"-{uuid.uuid4().hex[:6]}"
    except Exception:
        pass  # Branch doesn't exist, good

    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=base_branch.commit.sha,
    )
    logger.info("Created branch: %s", branch_name)

    # Commit workspace files
    workspace = Path(settings.workspace_dir)
    if not workspace.exists():
        logger.warning("Workspace directory not found")
        return None

    files_committed = 0
    for filepath in sorted(workspace.rglob("*")):
        if not filepath.is_file() or filepath.name.startswith("."):
            continue
        rel_path = str(filepath.relative_to(workspace))
        content = filepath.read_text(encoding="utf-8", errors="replace")
        repo.create_file(
            path=rel_path,
            message=f"Add {rel_path}",
            content=content,
            branch=branch_name,
        )
        files_committed += 1

    logger.info("Committed %d files to %s", files_committed, branch_name)

    # Build PR body
    body_parts = [
        f"## {spec.title}",
        "",
        f"**Complexity:** {spec.estimated_complexity}",
        "",
        "### Requirements",
        "",
    ]
    for i, req in enumerate(spec.requirements, 1):
        body_parts.append(f"{i}. {req}")

    body_parts.extend(["", "### Acceptance Criteria", ""])
    for i, ac in enumerate(spec.acceptance_criteria, 1):
        body_parts.append(f"{i}. {ac}")

    if review:
        score_pct = f"{review.score:.0%}"
        body_parts.extend([
            "",
            "### QA Review",
            "",
            f"**Verdict:** {review.verdict} | **Score:** {score_pct} | **Iterations:** {iteration}",
        ])
        if review.issues:
            body_parts.extend(["", "**Remaining issues:**"])
            for issue in review.issues:
                body_parts.append(f"- {issue}")

    body_parts.extend([
        "",
        "---",
        "*Generated by AI Dev Team (multi-agent system)*",
    ])

    pr = repo.create_pull(
        title=f"[AI Dev Team] {spec.title}",
        body="\n".join(body_parts),
        head=branch_name,
        base=settings.github_base_branch,
    )

    logger.info("Created PR #%d: %s", pr.number, pr.html_url)
    g.close()
    return pr.html_url
