"""Package pipeline results into timestamped output folders.

After each pipeline run, copies workspace files to:
  output/{timestamp}_{session_short}/
and generates a README.md with spec, code description, QA verdict.
"""

import logging
import shutil
from datetime import datetime
from pathlib import Path

from config import Settings
from schemas import CodeOutput, ReviewOutput, SpecOutput

logger = logging.getLogger("output")
settings = Settings()


def package_results(
    user_story: str,
    session_id: str,
    spec: SpecOutput | None,
    code: CodeOutput | None,
    review: ReviewOutput | None,
    iteration: int = 0,
    review_history: list[ReviewOutput] | None = None,
) -> str | None:
    """Copy workspace files to a timestamped output folder with README.

    Returns the output folder path, or None if no code was produced.
    """
    if not code:
        logger.warning("No code produced — skipping output packaging")
        return None

    timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    session_short = session_id[:8]
    folder_name = f"{timestamp}_{session_short}"

    output_dir = Path(settings.output_dir) / folder_name
    output_dir.mkdir(parents=True, exist_ok=True)

    # Copy workspace files
    workspace = Path(settings.workspace_dir)
    if workspace.exists():
        for item in workspace.iterdir():
            if item.name.startswith("."):
                continue
            dest = output_dir / item.name
            if item.is_dir():
                shutil.copytree(item, dest, dirs_exist_ok=True)
            else:
                shutil.copy2(item, dest)

    # Generate README.md
    readme = _build_readme(user_story, spec, code, review, iteration, review_history or [])
    (output_dir / "README.md").write_text(readme, encoding="utf-8")

    logger.info("Results packaged to %s", output_dir)
    return str(output_dir)


def clean_workspace() -> None:
    """Remove all files from workspace/ to prepare for next run."""
    workspace = Path(settings.workspace_dir)
    if workspace.exists():
        for item in workspace.iterdir():
            if item.is_dir():
                shutil.rmtree(item)
            else:
                item.unlink()
    workspace.mkdir(parents=True, exist_ok=True)
    logger.info("Workspace cleaned")


def _build_readme(
    user_story: str,
    spec: SpecOutput | None,
    code: CodeOutput | None,
    review: ReviewOutput | None,
    iteration: int,
    review_history: list[ReviewOutput],
) -> str:
    lines = [
        f"> Generated by AI Dev Team on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
    ]

    # User Story
    lines.extend(["# User Story", "", f"> {user_story}", ""])

    # Specification
    if spec:
        lines.extend([
            f"## Specification: {spec.title}",
            "",
            f"**Complexity:** {spec.estimated_complexity}",
            "",
            "### Requirements",
            "",
        ])
        for i, req in enumerate(spec.requirements, 1):
            lines.append(f"{i}. {req}")
        lines.extend(["", "### Acceptance Criteria", ""])
        for i, ac in enumerate(spec.acceptance_criteria, 1):
            lines.append(f"{i}. {ac}")
        lines.append("")

    # How to Run
    if code:
        main_file = None
        test_file = None
        has_requirements = False
        for f in code.files_created:
            if f == "requirements.txt":
                has_requirements = True
            elif "test" in f.lower():
                test_file = f
            elif f.endswith(".py") and main_file is None:
                main_file = f

        lines.extend(["## How to Run", ""])
        if code.description:
            lines.extend([code.description, ""])
        lines.append("```bash")
        lines.append("python -m venv .venv && source .venv/bin/activate")
        if has_requirements:
            lines.append("pip install -r requirements.txt")
        if main_file:
            lines.append(f"python {main_file}")
        lines.append("```")
        if test_file:
            lines.extend([
                "", "Run tests:", "",
                "```bash",
                f"python -m pytest {test_file} -v",
                "```",
            ])
        lines.append("")

    # Code
    if code:
        lines.extend([
            "## Generated Code",
            "",
            f"{code.description}",
            "",
            "**Files:**",
            "",
        ])
        for f in code.files_created:
            lines.append(f"- `{f}`")
        lines.extend([
            "",
            "### Source",
            "",
            "```python",
            code.source_code,
            "```",
            "",
        ])

    # QA Review
    if review:
        lines.extend([
            "## QA Review",
            "",
            f"**Verdict:** {review.verdict}",
            f"**Score:** {review.score:.0%}",
            f"**Iterations:** {iteration}",
            "",
        ])
        if review.issues:
            lines.append("### Issues")
            lines.append("")
            for issue in review.issues:
                lines.append(f"- {issue}")
            lines.append("")
        if review.suggestions:
            lines.append("### Suggestions")
            lines.append("")
            for sug in review.suggestions:
                lines.append(f"- {sug}")
            lines.append("")

    # Iteration History
    if len(review_history) > 1:
        lines.extend(["## Review History", ""])
        for i, r in enumerate(review_history, 1):
            lines.append(f"**Iteration {i}:** {r.verdict} (score: {r.score:.0%})")
            if r.issues:
                for issue in r.issues:
                    lines.append(f"  - {issue}")
        lines.append("")

    return "\n".join(lines)
